### ISSUE TITLE
Blank Password Bug

### ISSUE THREAD

**Issue by evilguc** [phatworx/devise_security_extension#40]
When you enter your old password on password_expired page and leave new password and confirmation blank you become signed in without changing password.
in PasswordExpiredController:

if resource.update_with_password(params[resource_name])

update_with_password reject blank password and password confirmation. because of that password passes validation (it juist does not exists) and user becomes signed in

**Comment by monfresh** [comment]
:100: I'm still seeing this as well with version 0.8.3

**Comment by stringsn88keys** [comment]
I'll check it out.

**Comment by monfresh** [comment]
Thanks, Thomas! I believe the fix is very simple, and @fidel submitted #48 two years ago :smile:

**Comment by stringsn88keys** [comment]
Thanks for the tip. I'm still getting my bearings in the code base (and how it relates to Devise) after stepping in because I needed to push an update for an issue I was seeing that was fixed but not pushed to RubyGems.

**Comment by stringsn88keys** [comment]
Merged the PR and I've bumped the minor version to 0.9.0.

**Comment by monfresh** [comment]
I just tried 0.9.0 and I'm getting this error when starting my Rails app:
```
cannot load such file -- devise_security_extension/models/database_authenticatable_patch (LoadError)
```
For some reason, this [require](https://github.com/phatworx/devise_security_extension/blob/master/lib/devise_security_extension.rb#L96) is not working.

Also, I would make sure to have tests for this feature before releasing a new version.

After testing this patch of `update_with_password` in my Rails app, I realized that it also overrides the behavior when editing the User profile, which is not what we want. Requiring the new password and password confirmation should only happen if the User has an expired password and they are on the expired password page. If their password has not expired, and if they are just editing their profile (like changing their email), then the new password and password confirmation should not be required.

Therefore, I think to solve this problem, the controller needs to use a custom method that is only called by that controller, instead of overriding Devise's `update_with_password`, which is used in other places.

**Comment by monfresh** [comment]
Alternatively, you could just improve the logic in `update_with_password`. This works for me, but I am not a Devise expert to say for sure that it covers all scenarios:

```ruby
def update_with_password(params, *options)
  current_password = params.delete(:current_password)

  if need_change_password?
    new_password = params[:password]
    new_password_confirmation = params[:password_confirmation]
  elsif params[:password].blank?
    params.delete(:password)
    params.delete(:password_confirmation) if params[:password_confirmation].blank?
  end

  result = if valid_password?(current_password)
    update_attributes(params, *options)
  else
    self.assign_attributes(params, *options)
    self.valid?
    self.errors.add(:current_password, current_password.blank? ? :blank : :invalid)
    self.errors.add(:password, new_password.blank? ? :blank : :invalid)
    self.errors.add(:password_confirmation, new_password_confirmation.blank? ? :blank : :invalid)
    false
  end

  clean_up_passwords
  result
end
```

**Comment by stringsn88keys** [comment]
Please try 0.9.1...  I had the same issue with 0.9.0 and noticed that I failed to add the file to the gemspec (it wasn't packaged in the gem at all).

**Comment by monfresh** [comment]
0.9.1 is not throwing the error, but it's still not solving the problem. When I run my tests, I now get this error when updating an expired password:
```
ActiveModel::ForbiddenAttributesError:
       ActiveModel::ForbiddenAttributesError
```
This project needs more tests to make sure everything is working as expected, especially for new features like this.

**Comment by stringsn88keys** [comment]
Agreed. I have a testing branch going, but it seems like most of my spare time has been spent putting out fires instead.

**Comment by monfresh** [comment]
So, I think I figured out the latest issue. The argument for `update_with_password` should be `resource_params` instead of `params[resource_name]`. That's what worked for me, and I didn't have to change the `update_with_password` method.

So, currently, the tests for my Rails app pass with 0.9.1, with the only difference being `resource_params` instead of `params[resource_name]`.

**Comment by monfresh** [comment]
I'll send a PR if you want.

**Comment by monfresh** [comment]
Here it is: https://github.com/phatworx/devise_security_extension/pull/116
